/**
 * 急診檢查項目表：Fast PE note 建議檢查時使用的「ERS 檢查驗系統」項目。
 *
 * 資料來源：2026-10-09 以急診身分從 ERS 檢查驗系統目錄整理（91 項，皆為可開立狀態）。
 * - `pfkey` 是系統的醫囑代碼；`name` 與系統顯示的醫囑名稱一致（含系統自己的逗號）。
 * - 只收錄 pfkey、名稱、檢體、頻率；不收價格與選單路徑。
 * - 系統若改名或停用，請重新整理這份表；`tests/v2/ed-orders.test.ts` 會檢查唯一性與格式。
 */

export type EdOrderGroup =
  | "heme"
  | "chem"
  | "cardiac"
  | "infect"
  | "urine"
  | "tox"
  | "endo"
  | "bedside"
  | "xray"
  | "ct";

export interface EdOrder {
  /** 穩定的內部 id（規則引用它；不要改名）。 */
  id: string;
  /** ERS 醫囑代碼。 */
  pfkey: string;
  /** ERS 顯示的醫囑名稱。 */
  name: string;
  group: EdOrderGroup;
  /** 檢體名稱；空字串 = 開單時需另外選擇檢體。 */
  spcnm: string;
  /** 檢體代碼；空字串 = 開單時需另外選擇檢體。 */
  spcnmCode: string;
}

/** 頻率：急診一律 URGENT。 */
export const ED_ORDER_FREQ = "URGENT";

export const ED_ORDERS: readonly EdOrder[] = [
  {
    id: "cbc_dc",
    pfkey: "9071715F",
    name: "CBC,DC,",
    group: "heme",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "pt",
    pfkey: "90680052",
    name: "PT,",
    group: "heme",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "aptt",
    pfkey: "90680051",
    name: "APTT,",
    group: "heme",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ddimer",
    pfkey: "99908079",
    name: "D-dimer(ER),[Blood]",
    group: "heme",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "fibrinogen",
    pfkey: "906HM014",
    name: "FIBRINOGEN,",
    group: "heme",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "crea",
    pfkey: "90691107",
    name: "Crea,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "bun",
    pfkey: "90691105",
    name: "BUN,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "na",
    pfkey: "90691113",
    name: "NA,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "k",
    pfkey: "90691114",
    name: "K,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "cl",
    pfkey: "90691115",
    name: "Cl,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ca",
    pfkey: "90691103",
    name: "Ca,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ca_free",
    pfkey: "90611207",
    name: "Ca++, free",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "mg",
    pfkey: "90609046",
    name: "Mg,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "phos",
    pfkey: "90609012",
    name: "P,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "glu",
    pfkey: "90691118",
    name: "Glu-AC,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "onetouch",
    pfkey: "99909005",
    name: "AC,One touch sugar(ER)",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ketone",
    pfkey: "90709137",
    name: "Ketone body",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "alt",
    pfkey: "90691111",
    name: "ALT,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ast",
    pfkey: "90691112",
    name: "AST,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "alb",
    pfkey: "90609038",
    name: "Alb,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "tbil",
    pfkey: "90691914",
    name: "Bil-T, (Bilirubin total)",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "dbil",
    pfkey: "90609030",
    name: "Bil-D, (Bilirubin direct)",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ggt",
    pfkey: "90609A31",
    name: "GGT,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "alp",
    pfkey: "90609027",
    name: "ALP,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ldh",
    pfkey: "90691110",
    name: "LDH,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "lipase",
    pfkey: "90611305",
    name: "Lipase,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "amylase",
    pfkey: "90691302",
    name: "Amylase,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ammonia",
    pfkey: "90661901",
    name: "Ammonia,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "lactate",
    pfkey: "90661908",
    name: "Lactate,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "crp",
    pfkey: "9068010F",
    name: "CRP,",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "vbg",
    pfkey: "99909041",
    name: "Blood gas(ER),[Blood]",
    group: "chem",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ck",
    pfkey: "90691120",
    name: "CK, (Creatine kinase)",
    group: "cardiac",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "tni",
    pfkey: "99909099",
    name: "TnI (ER),[Blood]",
    group: "cardiac",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "hs_tnt",
    pfkey: "90609099",
    name: "hs-cTnT",
    group: "cardiac",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "bnp",
    pfkey: "99912193",
    name: "NT-pro-BNP(ER),[Blood]",
    group: "cardiac",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "pct",
    pfkey: "99912192",
    name: "PCT(ER),[Blood]",
    group: "infect",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "bcx",
    pfkey: "Z9030001",
    name: "Blood culture 兩套 (18歲以上)",
    group: "infect",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "sputum_cx",
    pfkey: "Z9030002",
    name: "Sputum culture + Gram stain",
    group: "infect",
    spcnm: "Sputum",
    spcnmCode: "LAB0801",
  },
  {
    id: "urine_cx",
    pfkey: "90313H07",
    name: "ORDINARY CULTURE-A testcode",
    group: "infect",
    spcnm: "",
    spcnmCode: "",
  },
  {
    id: "flu",
    pfkey: "90614X65",
    name: "Influenza A+B Rapid Test (906)",
    group: "infect",
    spcnm: "Nasopharyngeal swab",
    spcnmCode: "LAB0804",
  },
  {
    id: "covid_ag",
    pfkey: "000FS001",
    name: "COVID-19 Antigen Rapid Test",
    group: "infect",
    spcnm: "Nasopharyngeal swab",
    spcnmCode: "LAB0804",
  },
  {
    id: "c_diff",
    pfkey: "90313F07",
    name: "C. difficile culture, stool",
    group: "infect",
    spcnm: "Stool",
    spcnmCode: "LAB0501",
  },
  {
    id: "stool_cx",
    pfkey: "90313007",
    name: "Salmonella/Shigella, stool",
    group: "infect",
    spcnm: "Stool",
    spcnmCode: "LAB0501",
  },
  {
    id: "urine_routine",
    pfkey: "90727250",
    name: "Urine routine",
    group: "urine",
    spcnm: "Urine",
    spcnmCode: "LAB0401",
  },
  {
    id: "urine_hcg",
    pfkey: "90727204",
    name: "HCG, urine",
    group: "urine",
    spcnm: "Urine",
    spcnmCode: "LAB0401",
  },
  {
    id: "bhcg",
    pfkey: "99927010",
    name: "BHCG(ER),[Blood]",
    group: "urine",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "stool_routine",
    pfkey: "90737351",
    name: "Stool routine,",
    group: "urine",
    spcnm: "Stool",
    spcnmCode: "LAB0501",
  },
  {
    id: "stool_ob",
    pfkey: "90737352",
    name: "OB, stool",
    group: "urine",
    spcnm: "Stool",
    spcnmCode: "LAB0501",
  },
  {
    id: "gastric_ob",
    pfkey: "90747403",
    name: "OB, Gastric juice or Vomit",
    group: "urine",
    spcnm: "Gastric juice or Vomit",
    spcnmCode: "LAB0504",
  },
  {
    id: "etoh",
    pfkey: "90610807",
    name: "Ethyl alcohol,",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "apap",
    pfkey: "90610803",
    name: "Acetaminophen",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "salicylate",
    pfkey: "90610508",
    name: "Salicylate (Aspirin)",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "urine_drug",
    pfkey: "Z9270003",
    name: "URINE BASIC DRUG SCREEN (NERVOUS SYSTE & CIRCULATORY)",
    group: "tox",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "digoxin",
    pfkey: "90610511",
    name: "Digoxin",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "theophylline",
    pfkey: "90610509",
    name: "Theophylline (Aminophylline)",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "phenytoin",
    pfkey: "90610502",
    name: "Phenytoin (Dilantin) total",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "valproate",
    pfkey: "90610510",
    name: "Valproic acid total",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "carbamazepine",
    pfkey: "90610501",
    name: "Carbamazepine total",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "lithium",
    pfkey: "90610520",
    name: "Lithium",
    group: "tox",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "tsh",
    pfkey: "90609112",
    name: "TSH,",
    group: "endo",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ft4",
    pfkey: "90609106",
    name: "T4 Free,",
    group: "endo",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "hba1c",
    pfkey: "90109A06",
    name: "A1C (HbA1C)",
    group: "endo",
    spcnm: "Blood",
    spcnmCode: "LAB0301",
  },
  {
    id: "ecg",
    pfkey: "99918001",
    name: "ECG(ER)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_cardiac",
    pfkey: "99919F05",
    name: "Sonography (cardiac)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_sob",
    pfkey: "99919K05",
    name: "Sonography (SOB)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_abd",
    pfkey: "99919J05",
    name: "Sonography (abdominal)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_dvt",
    pfkey: "99919G05",
    name: "Sonography (DVT)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_fast",
    pfkey: "99919005",
    name: "Sonography (FAST)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_aortic_renal",
    pfkey: "99919E05",
    name: "Sonography (aortic/renal)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_pelvic",
    pfkey: "99919I05",
    name: "Sonography (female pelvic)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "sono_fb",
    pfkey: "99919H05",
    name: "Sonography (foreign body)",
    group: "bedside",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "cxr_pa",
    pfkey: "15002010",
    name: "CHEST PA VIEW",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "cxr_port",
    pfkey: "15007430",
    name: "CHEST AP VIEW- PORTABLE",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "kub",
    pfkey: "15003010",
    name: "KUB- PLAIN",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "pelvis_xr",
    pfkey: "15006220",
    name: "PELVIS",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "cspine_xr",
    pfkey: "15006020",
    name: "C- SPINE AP- LATERAL",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "lspine_xr",
    pfkey: "15006110",
    name: "L- SPINE AP- LATERAL",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "skull_xr",
    pfkey: "15001220",
    name: "SKULL FILM (AP-LAT)",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "neck_soft_xr",
    pfkey: "15001210",
    name: "NECK  SOFT TISSUE",
    group: "xray",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
  {
    id: "ct_brain",
    pfkey: "15015A10",
    name: "CT/SCAN- BRAIN",
    group: "ct",
    spcnm: "HEAD",
    spcnmCode: "RAD0101",
  },
  {
    id: "cta_head_neck",
    pfkey: "15015241",
    name: "CT/ANGIOGRAM, HEAD & NECK",
    group: "ct",
    spcnm: "HEAD and NECK",
    spcnmCode: "RAD0100",
  },
  {
    id: "ct_perfusion",
    pfkey: "15015012",
    name: "CT/SCAN, BRAIN PERFUSION",
    group: "ct",
    spcnm: "HEAD and NECK",
    spcnmCode: "RAD0100",
  },
  {
    id: "ct_chest",
    pfkey: "15015A40",
    name: "CT/SCAN- CHEST",
    group: "ct",
    spcnm: "CHEST",
    spcnmCode: "RAD0201",
  },
  {
    id: "ct_upper_abd",
    pfkey: "15015A60",
    name: "CT/SCAN- UPPER ABDOMEN",
    group: "ct",
    spcnm: "UPPER ABDOMEN",
    spcnmCode: "RAD0203",
  },
  {
    id: "ct_pelvis",
    pfkey: "15015B10",
    name: "CT/SCAN- PELVIS",
    group: "ct",
    spcnm: "PELVIC CAVITY",
    spcnmCode: "RAD0204",
  },
  {
    id: "ct_cspine",
    pfkey: "15015B30",
    name: "CT/SCAN- C-SPINE",
    group: "ct",
    spcnm: "CERVICAL SPINE",
    spcnmCode: "RAD0301",
  },
  {
    id: "ct_lspine",
    pfkey: "15015B40",
    name: "CT/SCAN- L-SPINE",
    group: "ct",
    spcnm: "LUMBAR SPINE",
    spcnmCode: "RAD0303",
  },
  {
    id: "ct_face",
    pfkey: "15015C30",
    name: "CT/SCAN- FACE",
    group: "ct",
    spcnm: "HEAD and NECK",
    spcnmCode: "RAD0100",
  },
  {
    id: "ct_neck",
    pfkey: "15015C40",
    name: "CT/SCAN- NECK",
    group: "ct",
    spcnm: "NECK",
    spcnmCode: "RAD0102",
  },
  {
    id: "mri_brain",
    pfkey: "15020A10",
    name: "MRI/ BRAIN",
    group: "ct",
    spcnm: "HEAD",
    spcnmCode: "RAD0101",
  },
  {
    id: "doppler_limbs",
    pfkey: "15016460",
    name: "DOPPLER  LIMBS",
    group: "ct",
    spcnm: "Patient",
    spcnmCode: "0000000",
  },
];

const ORDER_BY_ID = new Map(ED_ORDERS.map((order) => [order.id, order]));

export function edOrder(id: string): EdOrder | undefined {
  return ORDER_BY_ID.get(id);
}

export const ED_ORDER_GROUP_LABELS: Readonly<Record<EdOrderGroup, string>> = {
  heme: "血液・凝血",
  chem: "生化",
  cardiac: "心臟指標",
  infect: "感染・培養",
  urine: "尿液・糞便",
  tox: "毒藥物・藥物濃度",
  endo: "內分泌",
  bedside: "心電圖・床邊超音波",
  xray: "X 光",
  ct: "CT・MRI・血管超音波",
};

export const ED_ORDER_GROUP_ORDER: readonly EdOrderGroup[] = [
  "heme",
  "chem",
  "cardiac",
  "infect",
  "urine",
  "tox",
  "endo",
  "bedside",
  "xray",
  "ct",
];
