import type { EdProblem, EdProblemGroup, IcdChoice } from "./types";

type ProblemInput = Omit<
  EdProblem,
  "characterize" | "askMore" | "must" | "peMore" | "peMust" | "icd"
> & {
  characterize?: string[];
  askMore?: string[];
  must?: string[];
  peMore?: string[];
  peMust?: string[];
  icd: IcdChoice[];
};

function problem(input: ProblemInput): EdProblem {
  return {
    characterize: [],
    askMore: [],
    must: [],
    peMore: [],
    peMust: [],
    ...input,
  };
}

const on = (code: string, desc: string): IcdChoice => ({ code, desc, defaultOn: true });
const off = (code: string, desc: string): IcdChoice => ({ code, desc });
const whenPick = (
  code: string,
  desc: string,
  item: string,
  option: string,
): IcdChoice => ({ code, desc, whenPick: { item, option } });

/**
 * 急診主訴（問題）清單。依歷史病歷 358 筆的主訴分布排序設計：
 * 腹痛、發燒、噁心嘔吐腹瀉、喘、頭暈、泌尿、外傷、胸痛、肢體腫痛、無力…
 *
 * ICD 一律以 unspecified／症狀碼為預設，診斷碼只作為「可勾選的備選」。
 */
export const ED_PROBLEMS: readonly EdProblem[] = [
  // ───────────── 全身 ─────────────
  problem({
    id: "fever",
    label: "發燒",
    cc: "fever",
    group: "全身代謝",
    characterize: ["fever", "onset"],
    ask: [
      "chills",
      "cough",
      "sputum",
      "sore_throat",
      "headache",
      "neck_stiff_h",
      "dyspnea",
      "chest_pain",
      "abd_pain",
      "vomiting",
      "diarrhea",
      "dysuria",
      "flank_pain",
      "rash",
      "wound",
      "sick_contact",
    ],
    askMore: [
      "rhinorrhea",
      "night_sweat",
      "wt_loss",
      "limb_pain",
      "frequency",
      "genital_discharge",
      "foley",
      "device",
      "abx_recent",
    ],
    must: ["headache", "neck_stiff_h", "dyspnea", "abd_pain", "dysuria", "cough"],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_throat",
      "neck_stiff",
      "chest_bs",
      "heart_murmur",
      "abd_tender",
      "abd_rebound",
      "back_cva",
      "ext_skin",
    ],
    peMore: [
      "heent_mucosa",
      "heent_ent",
      "ext_calf",
      "ext_motion",
      "gu_ext",
      "rectal_dre",
      "neuro_orient",
      "back_sore",
    ],
    peMust: ["chest_bs", "abd_tender", "ext_skin"],
    icd: [on("R50.9", "Fever, unspecified"), off("R68.83", "Chills (without fever)")],
  }),
  problem({
    id: "weakness",
    label: "全身無力／倦怠",
    cc: "general weakness",
    group: "全身代謝",
    characterize: ["malaise", "onset"],
    ask: [
      "fever",
      "anorexia",
      "vomiting",
      "diarrhea",
      "dysuria",
      "cough",
      "dyspnea",
      "chest_pain",
      "melena",
      "dizzy",
      "low_urine",
      "weak_focal",
    ],
    askMore: [
      "wt_loss",
      "night_sweat",
      "polyuria",
      "glucose_home",
      "dm_meds_issue",
      "anxiety",
      "insomnia",
      "head_strike",
    ],
    must: ["chest_pain", "melena", "weak_focal", "low_urine"],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_conj",
      "heent_mucosa",
      "chest_bs",
      "heart_rhythm",
      "abd_tender",
      "ext_edema",
      "neuro_mp",
    ],
    peMore: [
      "neuro_sensory",
      "neuro_cerebellar",
      "ext_skin",
      "rectal_dre",
      "heent_sclera",
    ],
    peMust: ["heent_conj", "heart_rhythm", "neuro_mp"],
    icd: [
      on("R53.1", "Weakness"),
      off("R53.83", "Other fatigue"),
      off("R53.81", "Other malaise"),
      off("R54", "Age-related physical debility"),
      off("M62.81", "Muscle weakness (generalized)"),
    ],
  }),
  problem({
    id: "bp_abnormal",
    label: "血壓異常",
    cc: "abnormal BP",
    ccFrom: "bp_type",
    ccMode: "replace",
    group: "全身代謝",
    characterize: ["bp_type", "bp_home", "bp_meds_issue"],
    ask: [
      "headache",
      "dizzy",
      "chest_pain",
      "dyspnea",
      "weak_focal",
      "slurred",
      "vision",
      "nausea",
      "vomiting",
      "melena",
    ],
    askMore: ["diarrhea", "epistaxis", "palpitation", "anticoag", "fever"],
    must: ["chest_pain", "headache", "weak_focal", "dyspnea", "vision", "melena"],
    pe: [
      "gc_look",
      "heent_pupil",
      "heent_mucosa",
      "chest_bs",
      "heart_rhythm",
      "heart_murmur",
      "ext_edema",
      "neuro_mp",
      "neuro_face",
      "neuro_speech",
    ],
    peMore: ["neck_jve", "abd_tender", "ext_pulse", "heent_conj", "ext_skin"],
    peMust: ["chest_bs", "heart_murmur", "neuro_mp"],
    icd: [
      {
        code: "R03.0",
        desc: "Elevated blood-pressure reading, without diagnosis of hypertension",
        defaultOn: true,
        offWhenPicked: "bp_type",
        whenPick: { item: "bp_type", option: "偏高" },
      },
      whenPick("I95.9", "Hypotension, unspecified", "bp_type", "偏低"),
      off("I10", "Essential (primary) hypertension"),
    ],
  }),
  problem({
    id: "glucose",
    label: "血糖異常",
    cc: "abnormal glucose",
    ccFrom: "glu_type",
    ccMode: "replace",
    group: "全身代謝",
    characterize: ["glu_type", "glucose_home", "dm_meds_issue"],
    ask: [
      "polyuria",
      "vomiting",
      "abd_pain",
      "fever",
      "confusion",
      "dizzy",
      "cold_sweat",
      "anorexia",
      "diarrhea",
      "cough",
      "dysuria",
      "wound",
      "chest_pain",
      "dyspnea",
    ],
    must: ["dm_meds_issue", "vomiting", "abd_pain", "confusion", "fever"],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_mucosa",
      "chest_pattern",
      "chest_bs",
      "heart_rhythm",
      "abd_tender",
      "ext_skin",
      "ext_pulse",
      "neuro_orient",
    ],
    peMore: ["neuro_mp", "neuro_sensory"],
    peMust: ["heent_mucosa", "chest_pattern", "abd_tender"],
    icd: [
      {
        code: "R73.9",
        desc: "Hyperglycemia, unspecified",
        defaultOn: true,
        offWhenPicked: "glu_type",
        whenPick: { item: "glu_type", option: "偏高" },
      },
      whenPick("E16.2", "Hypoglycemia, unspecified", "glu_type", "偏低"),
    ],
  }),
  problem({
    id: "lab_referral",
    label: "檢驗異常／門診轉入",
    cc: "referred for abnormal lab",
    group: "全身代謝",
    characterize: ["onset"],
    ask: [
      "fever",
      "dyspnea",
      "chest_pain",
      "abd_pain",
      "vomiting",
      "diarrhea",
      "dysuria",
      "cough",
    ],
    pe: ["gc_look", "chest_bs", "heart_rhythm", "abd_tender", "ext_edema", "neuro_mp"],
    icd: [
      on("R79.89", "Other specified abnormal findings of blood chemistry"),
      off("D72.829", "Elevated white blood cell count, unspecified"),
      off("R68.89", "Other general symptoms and signs"),
    ],
  }),

  // ───────────── 心肺 ─────────────
  problem({
    id: "chest_pain",
    label: "胸痛／胸悶",
    cc: "chest pain",
    ccFrom: "chest_quality",
    ccMode: "replace",
    group: "心肺",
    pain: true,
    characterize: [
      "chest_quality",
      "onset",
      "chest_radiate",
      "chest_exert",
      "chest_position",
    ],
    ask: [
      "dyspnea",
      "cold_sweat",
      "nausea",
      "palpitation",
      "syncope",
      "pleuritic",
      "cough",
      "fever",
      "calf_pain",
      "immobil",
      "heartburn",
      "food_trigger",
      "anticoag",
    ],
    askMore: [
      "vomiting",
      "dizzy",
      "leg_edema",
      "hemoptysis",
      "orthopnea",
      "weak_focal",
      "numb",
    ],
    must: [
      "chest_quality",
      "chest_radiate",
      "dyspnea",
      "cold_sweat",
      "syncope",
      "immobil",
      "pleuritic",
    ],
    pe: [
      "gc_look",
      "chest_pattern",
      "chest_bs",
      "heart_rhythm",
      "heart_murmur",
      "chest_wall",
      "abd_tender",
      "ext_edema",
      "ext_calf",
    ],
    peMore: ["neck_jve", "ext_pulse", "neuro_mp", "chest_expansion", "abd_mass"],
    peMust: ["chest_bs", "heart_rhythm", "heart_murmur", "chest_wall"],
    icd: [
      on("R07.9", "Chest pain, unspecified"),
      off("R07.89", "Other chest pain"),
      off("R07.1", "Chest pain on breathing"),
      off("R07.2", "Precordial pain"),
    ],
  }),
  problem({
    id: "dyspnea",
    label: "喘／呼吸困難",
    cc: "dyspnea",
    group: "心肺",
    characterize: ["dysp_trigger", "onset"],
    ask: [
      "orthopnea",
      "cough",
      "sputum",
      "fever",
      "chest_pain",
      "wheeze",
      "leg_edema",
      "hemoptysis",
      "calf_pain",
      "immobil",
      "palpitation",
      "lip_swell",
      "sore_throat",
    ],
    askMore: [
      "allergen",
      "wt_loss",
      "night_sweat",
      "anticoag",
      "cold_sweat",
      "vomiting",
    ],
    must: ["chest_pain", "wheeze", "immobil", "lip_swell", "orthopnea"],
    pe: [
      "gc_look",
      "gc_gcs",
      "neck_accessory",
      "neck_jve",
      "chest_pattern",
      "chest_bs",
      "heart_rhythm",
      "heart_murmur",
      "ext_edema",
      "ext_calf",
      "ext_skin",
    ],
    peMore: ["heent_throat", "chest_expansion", "ext_pulse", "neuro_orient"],
    peMust: ["chest_pattern", "chest_bs", "neck_accessory"],
    icd: [
      on("R06.00", "Dyspnea, unspecified"),
      off("R06.02", "Shortness of breath"),
      off("R06.89", "Other abnormalities of breathing"),
      off("R09.02", "Hypoxemia"),
    ],
  }),
  problem({
    id: "palpitation",
    label: "心悸",
    cc: "palpitation",
    group: "心肺",
    characterize: ["palp_pattern", "onset"],
    ask: [
      "chest_pain",
      "dyspnea",
      "syncope",
      "presyncope",
      "dizzy",
      "cold_sweat",
      "anxiety",
      "fever",
      "vomiting",
      "diarrhea",
      "substance",
    ],
    askMore: ["wt_loss", "anticoag", "alcohol"],
    must: ["syncope", "chest_pain", "dyspnea"],
    pe: [
      "gc_look",
      "heart_rhythm",
      "heart_murmur",
      "chest_bs",
      "neck_jve",
      "ext_edema",
    ],
    peMore: ["neck_lap", "heent_mucosa", "heent_conj"],
    peMust: ["heart_rhythm"],
    icd: [
      on("R00.2", "Palpitations"),
      off("R00.0", "Tachycardia, unspecified"),
      off("R00.1", "Bradycardia, unspecified"),
      off("R00.8", "Other abnormalities of heart beat"),
    ],
  }),
  problem({
    id: "syncope",
    label: "暈厥",
    cc: "syncope",
    group: "心肺",
    characterize: ["syncope_trigger", "onset"],
    ask: [
      "presyncope",
      "palpitation",
      "chest_pain",
      "dyspnea",
      "cold_sweat",
      "headache",
      "head_strike",
      "seizure",
      "vomiting",
      "diarrhea",
      "melena",
      "pregnancy_possible",
      "anticoag",
      "dm_meds_issue",
    ],
    askMore: [
      "amnesia",
      "confusion",
      "neck_back_pain",
      "alcohol",
      "polyuria",
      "bp_meds_issue",
    ],
    must: [
      "palpitation",
      "chest_pain",
      "head_strike",
      "anticoag",
      "pregnancy_possible",
      "melena",
    ],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_conj",
      "heent_head_trauma",
      "heart_rhythm",
      "heart_murmur",
      "chest_bs",
      "abd_tender",
    ],
    peMore: [
      "neck_jve",
      "neuro_mp",
      "neuro_speech",
      "neuro_face",
      "ext_pulse",
      "ext_edema",
      "rectal_dre",
    ],
    peMust: ["heart_rhythm", "heart_murmur", "heent_conj"],
    icd: [on("R55", "Syncope and collapse"), off("R42", "Dizziness and giddiness")],
  }),
  problem({
    id: "cough_uri",
    label: "咳嗽／上呼吸道感染",
    cc: "cough",
    group: "心肺",
    characterize: ["onset", "cough", "sputum"],
    ask: [
      "fever",
      "chills",
      "dyspnea",
      "wheeze",
      "sore_throat",
      "rhinorrhea",
      "chest_pain",
      "hemoptysis",
      "sick_contact",
      "pleuritic",
    ],
    askMore: ["wt_loss", "night_sweat", "leg_edema", "orthopnea", "heartburn"],
    must: ["dyspnea", "hemoptysis", "chest_pain"],
    pe: [
      "gc_look",
      "heent_throat",
      "heent_ent",
      "neck_lap",
      "chest_pattern",
      "chest_bs",
      "heart_rhythm",
    ],
    peMore: ["neck_accessory", "ext_edema", "ext_skin"],
    peMust: ["chest_bs"],
    icd: [
      on("R05.9", "Cough, unspecified"),
      off("J06.9", "Acute upper respiratory infection, unspecified"),
      off("R09.81", "Nasal congestion"),
    ],
  }),
  problem({
    id: "ent",
    label: "耳鼻喉（喉痛、耳痛、鼻血、吞嚥）",
    cc: "ENT symptom",
    ccFrom: "ent_type",
    ccMode: "replace",
    group: "五官",
    characterize: ["ent_type", "onset"],
    ask: [
      "fever",
      "sore_throat",
      "rhinorrhea",
      "cough",
      "dysphagia",
      "hearing",
      "lip_swell",
      "dyspnea",
      "epistaxis",
      "anticoag",
      "head_strike",
    ],
    askMore: ["wt_loss", "night_sweat", "gum_bleed", "headache", "neck_stiff_h"],
    must: ["dyspnea", "lip_swell", "dysphagia", "anticoag"],
    pe: ["heent_throat", "heent_ent", "neck_lap", "neck_stiff", "chest_bs"],
    peMore: ["heent_mucosa", "heent_pupil", "ext_skin"],
    peMust: ["heent_throat"],
    icd: [
      on("J02.9", "Acute pharyngitis, unspecified"),
      whenPick("H92.09", "Otalgia, unspecified ear", "ent_type", "耳痛"),
      whenPick("R04.0", "Epistaxis", "ent_type", "流鼻血"),
      whenPick("R13.10", "Dysphagia, unspecified", "ent_type", "吞嚥困難／梗到"),
      whenPick("R49.0", "Dysphonia", "ent_type", "聲音沙啞"),
      whenPick(
        "R22.1",
        "Localized swelling, mass and lump, neck",
        "ent_type",
        "頸部腫塊",
      ),
      whenPick(
        "K08.89",
        "Other specified disorders of teeth and supporting structures",
        "ent_type",
        "牙痛",
      ),
    ],
  }),
  problem({
    id: "eye",
    label: "眼睛（視力、眼痛、紅眼）",
    cc: "eye symptom",
    ccFrom: "eye_type",
    ccMode: "replace",
    group: "五官",
    characterize: ["eye_type", "onset"],
    ask: [
      "headache",
      "vision",
      "photophobia",
      "head_strike",
      "nausea",
      "vomiting",
      "weak_focal",
      "dizzy",
      "fever",
      "rash",
    ],
    must: ["headache", "weak_focal", "head_strike", "nausea", "vomiting"],
    pe: ["heent_eye", "heent_conj", "heent_pupil", "neuro_face", "neck_stiff"],
    peMore: ["heent_nystagmus", "neuro_mp"],
    peMust: ["heent_eye", "heent_pupil"],
    icd: [
      on("H53.9", "Unspecified visual disturbance"),
      off("H57.10", "Ocular pain, unspecified eye"),
      off("H53.2", "Diplopia"),
      off("H10.9", "Unspecified conjunctivitis"),
    ],
  }),

  // ───────────── 消化 ─────────────
  problem({
    id: "abd_pain",
    label: "腹痛",
    cc: "abd pain",
    ccFrom: "abd_site",
    group: "消化",
    pain: true,
    characterize: ["abd_site", "abd_quality", "onset", "abd_migrate"],
    ask: [
      "nausea",
      "vomiting",
      "diarrhea",
      "constipation",
      "melena",
      "hematochezia",
      "fever",
      "food_trigger",
      "dysuria",
      "hematuria",
      "vag_bleed",
      "pregnancy_possible",
      "lmp",
      "chest_pain",
      "dyspnea",
    ],
    askMore: [
      "alcohol",
      "nsaid_steroid",
      "abd_surgery",
      "bloating",
      "no_flatus",
      "jaundice",
      "heartburn",
      "flank_pain",
      "anticoag",
    ],
    must: ["vomiting", "melena", "fever", "pregnancy_possible", "chest_pain"],
    pe: [
      "gc_look",
      "abd_inspect",
      "abd_bs",
      "abd_tender",
      "abd_guard",
      "abd_rebound",
      "back_cva",
    ],
    peMore: [
      "abd_murphy",
      "abd_appendix",
      "abd_mass",
      "gu_ext",
      "gu_bladder",
      "rectal_dre",
      "chest_bs",
      "ext_skin",
      "heent_sclera",
      "heent_mucosa",
    ],
    peMust: ["abd_tender", "abd_guard", "abd_rebound"],
    icd: [
      on("R10.9", "Unspecified abdominal pain"),
      off("R10.10", "Upper abdominal pain, unspecified"),
      off("R10.30", "Lower abdominal pain, unspecified"),
      off("R10.84", "Generalized abdominal pain"),
      off("R10.13", "Epigastric pain"),
    ],
  }),
  problem({
    id: "nausea_vomiting",
    label: "噁心／嘔吐",
    cc: "N/V",
    group: "消化",
    characterize: ["onset", "vomiting", "nausea"],
    ask: [
      "abd_pain",
      "diarrhea",
      "fever",
      "hematemesis",
      "melena",
      "headache",
      "dizzy",
      "food_trigger",
      "pregnancy_possible",
      "lmp",
      "dysuria",
      "chest_pain",
      "no_flatus",
      "alcohol",
    ],
    askMore: [
      "nsaid_steroid",
      "abd_surgery",
      "sick_contact",
      "vision",
      "neck_stiff_h",
      "head_strike",
    ],
    must: ["hematemesis", "abd_pain", "headache", "pregnancy_possible", "no_flatus"],
    pe: [
      "gc_look",
      "heent_mucosa",
      "abd_inspect",
      "abd_bs",
      "abd_tender",
      "abd_guard",
      "abd_rebound",
    ],
    peMore: [
      "back_cva",
      "neuro_cerebellar",
      "heent_nystagmus",
      "rectal_dre",
      "abd_mass",
      "neuro_orient",
    ],
    peMust: ["heent_mucosa", "abd_tender"],
    icd: [
      on("R11.2", "Nausea with vomiting, unspecified"),
      off("R11.0", "Nausea"),
      off("R11.10", "Vomiting, unspecified"),
    ],
  }),
  problem({
    id: "diarrhea",
    label: "腹瀉",
    cc: "diarrhea",
    group: "消化",
    characterize: ["onset", "diarrhea"],
    ask: [
      "hematochezia",
      "melena",
      "abd_pain",
      "vomiting",
      "fever",
      "food_trigger",
      "sick_contact",
      "abx_recent",
      "dysuria",
    ],
    askMore: ["wt_loss", "night_sweat", "nsaid_steroid", "alcohol"],
    must: ["hematochezia", "fever", "abx_recent"],
    pe: [
      "gc_look",
      "heent_mucosa",
      "abd_inspect",
      "abd_bs",
      "abd_tender",
      "abd_rebound",
    ],
    peMore: ["rectal_dre", "ext_pulse", "abd_mass", "neuro_orient"],
    peMust: ["heent_mucosa", "abd_tender"],
    icd: [
      on("R19.7", "Diarrhea, unspecified"),
      off("A09", "Infectious gastroenteritis and colitis, unspecified"),
      off("K52.9", "Noninfective gastroenteritis and colitis, unspecified"),
    ],
  }),
  problem({
    id: "constipation_bloating",
    label: "便秘／腹脹",
    cc: "constipation/abd distension",
    group: "消化",
    characterize: ["onset", "constipation", "bloating"],
    ask: [
      "no_flatus",
      "vomiting",
      "abd_pain",
      "melena",
      "hematochezia",
      "abd_surgery",
      "wt_loss",
    ],
    must: ["no_flatus", "vomiting", "abd_surgery"],
    pe: ["abd_inspect", "abd_bs", "abd_tender", "abd_rebound"],
    peMore: ["abd_mass", "rectal_dre", "gu_bladder"],
    peMust: ["abd_inspect", "abd_bs"],
    icd: [
      on("K59.00", "Constipation, unspecified"),
      off("R14.0", "Abdominal distension (gaseous)"),
      off(
        "K56.609",
        "Unspecified intestinal obstruction, unspecified as to partial versus complete obstruction",
      ),
    ],
  }),
  problem({
    id: "gi_bleed",
    label: "吐血／黑便／血便",
    cc: "GI bleeding",
    ccFrom: "gib_type",
    ccMode: "replace",
    group: "消化",
    characterize: ["gib_type", "onset", "melena", "hematochezia", "hematemesis"],
    ask: [
      "dizzy",
      "presyncope",
      "syncope",
      "dyspnea",
      "chest_pain",
      "abd_pain",
      "vomiting",
      "nsaid_steroid",
      "alcohol",
      "anticoag",
      "wt_loss",
    ],
    askMore: ["abd_surgery", "jaundice", "fever"],
    must: ["anticoag", "syncope", "hematemesis", "melena"],
    pe: [
      "gc_look",
      "heent_conj",
      "heent_mucosa",
      "heart_rhythm",
      "abd_tender",
      "rectal_dre",
      "ext_pulse",
    ],
    peMore: ["abd_mass", "ext_skin", "abd_inspect", "abd_rebound"],
    peMust: ["rectal_dre", "heent_conj"],
    icd: [
      on("K92.2", "Gastrointestinal hemorrhage, unspecified"),
      off("K92.1", "Melena"),
      off("K92.0", "Hematemesis"),
      off("K62.5", "Hemorrhage of anus and rectum"),
    ],
  }),
  problem({
    id: "jaundice",
    label: "黃疸",
    cc: "jaundice",
    group: "消化",
    characterize: ["onset", "jaundice"],
    ask: [
      "abd_pain",
      "fever",
      "chills",
      "nausea",
      "vomiting",
      "alcohol",
      "anorexia",
      "wt_loss",
      "itch",
      "melena",
    ],
    askMore: ["nsaid_steroid", "sick_contact"],
    must: ["fever", "abd_pain"],
    pe: ["gc_look", "heent_sclera", "abd_tender", "abd_murphy", "abd_mass", "ext_skin"],
    peMore: ["abd_rebound", "neuro_orient", "ext_edema"],
    peMust: ["heent_sclera", "abd_murphy"],
    icd: [on("R17", "Unspecified jaundice")],
  }),

  // ───────────── 泌尿婦產 ─────────────
  problem({
    id: "urinary",
    label: "泌尿症狀（解尿痛、血尿、解不出）",
    cc: "urinary symptom",
    ccFrom: "uri_type",
    ccMode: "replace",
    group: "泌尿婦產",
    characterize: ["uri_type", "onset"],
    ask: [
      "dysuria",
      "frequency",
      "hematuria",
      "flank_pain",
      "fever",
      "chills",
      "nausea",
      "vomiting",
      "abd_pain",
      "low_urine",
      "retention",
      "genital_discharge",
      "foley",
      "anticoag",
      "pregnancy_possible",
    ],
    askMore: ["wt_loss", "lmp", "vag_bleed"],
    must: ["fever", "flank_pain", "retention", "anticoag", "pregnancy_possible"],
    pe: ["gc_look", "abd_tender", "gu_bladder", "back_cva", "gu_ext"],
    peMore: ["abd_rebound", "abd_mass", "rectal_dre", "ext_edema", "heent_mucosa"],
    peMust: ["back_cva", "gu_bladder"],
    icd: [
      {
        code: "R30.0",
        desc: "Dysuria",
        defaultOn: true,
        offWhenPicked: "uri_type",
        whenPick: { item: "uri_type", option: "解尿疼痛" },
      },
      whenPick("R35.0", "Frequency of micturition", "uri_type", "頻尿"),
      whenPick("R31.9", "Hematuria, unspecified", "uri_type", "血尿"),
      whenPick("R33.9", "Retention of urine, unspecified", "uri_type", "解不出來"),
      whenPick("R10.9", "Unspecified abdominal pain", "uri_type", "腰／側腹痛"),
      whenPick("R34", "Anuria and oliguria", "uri_type", "尿量減少"),
      off("N39.0", "Urinary tract infection, site not specified"),
    ],
  }),
  problem({
    id: "gyn",
    label: "陰道出血／婦科下腹痛",
    cc: "vaginal bleeding",
    group: "泌尿婦產",
    pain: true,
    characterize: ["onset", "vag_bleed", "lmp", "pregnancy_possible"],
    ask: [
      "abd_pain",
      "genital_discharge",
      "dizzy",
      "presyncope",
      "syncope",
      "fever",
      "dysuria",
      "nausea",
      "vomiting",
      "anticoag",
    ],
    askMore: ["hematuria", "constipation"],
    must: ["lmp", "pregnancy_possible", "presyncope", "abd_pain"],
    pe: [
      "gc_look",
      "heent_conj",
      "abd_tender",
      "abd_rebound",
      "gu_ext",
      "gu_bladder",
      "heart_rhythm",
    ],
    peMore: ["back_cva", "abd_mass", "ext_pulse"],
    peMust: ["abd_tender", "gu_ext"],
    icd: [
      on("N93.9", "Abnormal uterine and vaginal bleeding, unspecified"),
      off("R10.30", "Lower abdominal pain, unspecified"),
      off(
        "N94.89",
        "Other specified conditions associated with female genital organs and menstrual cycle",
      ),
    ],
  }),

  // ───────────── 神經 ─────────────
  problem({
    id: "dizziness",
    label: "頭暈",
    cc: "dizziness",
    ccFrom: "dizzy_kind",
    ccMode: "replace",
    group: "神經",
    characterize: ["dizzy_kind", "onset", "dizzy_position"],
    ask: [
      "nausea",
      "vomiting",
      "headache",
      "hearing",
      "vision",
      "weak_focal",
      "numb",
      "slurred",
      "gait",
      "presyncope",
      "palpitation",
      "chest_pain",
      "melena",
      "lkw",
    ],
    askMore: [
      "facial_droop",
      "dyspnea",
      "fever",
      "head_strike",
      "anticoag",
      "dm_meds_issue",
      "bp_meds_issue",
      "pregnancy_possible",
    ],
    must: ["weak_focal", "slurred", "vision", "gait", "headache", "lkw", "chest_pain"],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_pupil",
      "heent_nystagmus",
      "heent_conj",
      "neuro_mp",
      "neuro_sensory",
      "neuro_face",
      "neuro_speech",
      "neuro_cerebellar",
      "heart_rhythm",
    ],
    peMore: [
      "neuro_dixhallpike",
      "neuro_babinski",
      "heent_ent",
      "neck_stiff",
      "chest_bs",
      "neuro_orient",
    ],
    peMust: ["heent_nystagmus", "neuro_mp", "neuro_face", "neuro_cerebellar"],
    icd: [on("R42", "Dizziness and giddiness"), off("R26.81", "Unsteadiness on feet")],
  }),
  problem({
    id: "headache",
    label: "頭痛",
    cc: "headache",
    group: "神經",
    pain: true,
    characterize: ["onset", "headache_worst"],
    ask: [
      "nausea",
      "vomiting",
      "fever",
      "neck_stiff_h",
      "photophobia",
      "vision",
      "weak_focal",
      "numb",
      "slurred",
      "dizzy",
      "head_strike",
      "loc",
      "seizure",
      "anticoag",
      "cough",
      "rhinorrhea",
    ],
    askMore: ["similar_episode", "hearing", "rash", "sick_contact"],
    must: [
      "headache_worst",
      "fever",
      "neck_stiff_h",
      "weak_focal",
      "head_strike",
      "anticoag",
      "vision",
    ],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_pupil",
      "heent_head_trauma",
      "heent_ent",
      "neck_stiff",
      "neuro_mp",
      "neuro_face",
      "neuro_cerebellar",
      "neuro_sensory",
    ],
    peMore: [
      "heent_throat",
      "heent_nystagmus",
      "neuro_speech",
      "ext_skin",
      "neuro_orient",
    ],
    peMust: ["neck_stiff", "heent_pupil", "neuro_mp"],
    icd: [on("R51.9", "Headache, unspecified")],
  }),
  problem({
    id: "focal_neuro",
    label: "單側無力／麻／言語障礙／臉歪",
    cc: "focal weakness",
    group: "神經",
    characterize: [
      "lkw",
      "onset",
      "weak_focal",
      "numb",
      "slurred",
      "facial_droop",
      "vision",
    ],
    ask: [
      "headache",
      "dizzy",
      "gait",
      "nausea",
      "vomiting",
      "seizure",
      "confusion",
      "chest_pain",
      "palpitation",
      "head_strike",
      "anticoag",
      "fever",
    ],
    askMore: ["neck_back_pain", "low_urine", "retention", "dm_meds_issue", "hearing"],
    must: ["lkw", "anticoag", "head_strike", "headache", "seizure"],
    pe: [
      "gc_gcs",
      "heent_pupil",
      "heent_nystagmus",
      "neck_stiff",
      "neuro_orient",
      "neuro_mp",
      "neuro_sensory",
      "neuro_face",
      "neuro_speech",
      "neuro_cerebellar",
      "neuro_babinski",
      "heart_rhythm",
    ],
    peMore: ["heent_head_trauma", "neck_spine", "back_spine", "chest_bs", "ext_pulse"],
    peMust: [
      "neuro_mp",
      "neuro_face",
      "neuro_speech",
      "neuro_cerebellar",
      "heart_rhythm",
    ],
    icd: [
      on("R53.1", "Weakness"),
      off("R29.810", "Facial weakness"),
      off("R47.9", "Unspecified speech disturbances"),
      off("R20.2", "Paresthesia of skin"),
      off("R29.818", "Other symptoms and signs involving the nervous system"),
    ],
  }),
  problem({
    id: "ams",
    label: "意識改變",
    cc: "altered mental status",
    group: "神經",
    characterize: ["onset", "confusion"],
    ask: [
      "fever",
      "headache",
      "seizure",
      "head_strike",
      "vomiting",
      "diarrhea",
      "dm_meds_issue",
      "glucose_home",
      "self_harm",
      "alcohol",
      "substance",
      "cough",
      "dysuria",
      "anticoag",
      "weak_focal",
      "slurred",
      "chest_pain",
    ],
    askMore: ["low_urine", "wt_loss"],
    must: [
      "head_strike",
      "dm_meds_issue",
      "self_harm",
      "fever",
      "seizure",
      "weak_focal",
    ],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_pupil",
      "heent_mucosa",
      "neck_stiff",
      "chest_bs",
      "heart_rhythm",
      "abd_tender",
      "ext_skin",
      "neuro_orient",
      "neuro_mp",
      "neuro_face",
      "neuro_babinski",
    ],
    peMore: [
      "heent_head_trauma",
      "ext_edema",
      "rectal_dre",
      "neuro_speech",
      "back_sore",
    ],
    peMust: ["gc_gcs", "heent_pupil", "neck_stiff", "neuro_mp"],
    icd: [
      on("R41.82", "Altered mental status, unspecified"),
      off("R40.0", "Somnolence"),
      off("R41.0", "Disorientation, unspecified"),
    ],
  }),
  problem({
    id: "seizure",
    label: "抽搐",
    cc: "seizure",
    group: "神經",
    characterize: ["seizure", "onset"],
    ask: [
      "loc",
      "confusion",
      "head_strike",
      "headache",
      "fever",
      "vomiting",
      "dm_meds_issue",
      "alcohol",
      "substance",
      "anticoag",
      "weak_focal",
      "insomnia",
    ],
    askMore: ["similar_episode", "neck_stiff_h", "pregnancy_possible"],
    must: ["head_strike", "fever", "alcohol", "dm_meds_issue", "anticoag"],
    pe: [
      "gc_gcs",
      "heent_pupil",
      "heent_head_trauma",
      "neck_stiff",
      "neuro_orient",
      "neuro_mp",
      "neuro_face",
      "neuro_babinski",
      "heart_rhythm",
    ],
    peMore: ["ext_motion", "chest_bs", "ext_skin"],
    peMust: ["gc_gcs", "neuro_mp", "heent_head_trauma"],
    icd: [
      on("R56.9", "Unspecified convulsions"),
      off(
        "G40.909",
        "Epilepsy, unspecified, not intractable, without status epilepticus",
      ),
    ],
  }),

  // ───────────── 外傷・皮膚・骨科 ─────────────
  problem({
    id: "trauma",
    label: "外傷／跌倒",
    cc: "trauma",
    ccFrom: "mechanism",
    ccMode: "replace",
    group: "外傷皮膚骨科",
    pain: true,
    characterize: ["mechanism", "injury_time", "injury_site"],
    ask: [
      "head_strike",
      "loc",
      "amnesia",
      "vomiting",
      "headache",
      "neck_back_pain",
      "walk_after",
      "wound_bleed",
      "chest_pain",
      "dyspnea",
      "abd_pain",
      "numb",
      "weak_focal",
      "anticoag",
      "syncope",
      "presyncope",
      "alcohol",
    ],
    askMore: ["dizzy", "palpitation", "hematuria", "limb_pain", "tetanus", "vision"],
    must: [
      "head_strike",
      "loc",
      "anticoag",
      "neck_back_pain",
      "syncope",
      "chest_pain",
      "abd_pain",
    ],
    pe: [
      "gc_gcs",
      "heent_pupil",
      "heent_head_trauma",
      "neck_spine",
      "chest_wall",
      "chest_expansion",
      "chest_bs",
      "abd_tender",
      "back_spine",
      "ext_motion",
      "ext_pulse",
      "ext_skin",
      "neuro_mp",
      "neuro_sensory",
    ],
    peMore: [
      "heent_ent",
      "gu_ext",
      "rectal_dre",
      "neuro_face",
      "gu_bladder",
      "abd_rebound",
      "heart_rhythm",
    ],
    peMust: [
      "gc_gcs",
      "heent_head_trauma",
      "neck_spine",
      "chest_wall",
      "abd_tender",
      "back_spine",
      "ext_motion",
      "neuro_mp",
    ],
    icd: [
      on("T14.90XA", "Injury, unspecified, initial encounter"),
      off("W19.XXXA", "Unspecified fall, initial encounter"),
      off("S09.90XA", "Unspecified injury of head, initial encounter"),
      off(
        "V89.2XXA",
        "Person injured in unspecified motor-vehicle accident, traffic, initial encounter",
      ),
    ],
  }),
  problem({
    id: "back_pain",
    label: "背痛／腰痛／頸痛",
    cc: "back pain",
    ccFrom: "back_site",
    ccMode: "replace",
    group: "外傷皮膚骨科",
    pain: true,
    characterize: ["back_site", "onset", "back_radiate"],
    ask: [
      "weak_focal",
      "numb",
      "retention",
      "low_urine",
      "fever",
      "flank_pain",
      "hematuria",
      "abd_pain",
      "chest_pain",
      "wt_loss",
      "anticoag",
    ],
    askMore: ["dysuria", "vomiting", "night_sweat", "steroid_use", "head_strike"],
    must: ["weak_focal", "retention", "fever", "chest_pain", "wt_loss"],
    pe: [
      "gc_look",
      "back_spine",
      "back_slr",
      "back_cva",
      "abd_tender",
      "neuro_mp",
      "neuro_sensory",
      "ext_pulse",
    ],
    peMore: [
      "abd_mass",
      "neuro_babinski",
      "ext_motion",
      "gu_bladder",
      "rectal_dre",
      "back_sore",
    ],
    peMust: ["back_spine", "neuro_mp", "neuro_sensory"],
    icd: [
      on("M54.9", "Dorsalgia, unspecified"),
      whenPick("M54.50", "Low back pain, unspecified", "back_site", "下背／腰"),
      whenPick("M54.2", "Cervicalgia", "back_site", "頸"),
      whenPick("M54.6", "Pain in thoracic spine", "back_site", "上背／胸背"),
      off("M54.16", "Radiculopathy, lumbar region"),
    ],
  }),
  problem({
    id: "limb",
    label: "肢體疼痛／腫脹／紅熱",
    cc: "limb pain/swelling",
    group: "外傷皮膚骨科",
    pain: true,
    characterize: ["onset", "limb_pain", "swelling", "redness"],
    ask: [
      "fever",
      "chills",
      "wound",
      "calf_pain",
      "immobil",
      "leg_edema",
      "chest_pain",
      "dyspnea",
      "numb",
      "anticoag",
    ],
    askMore: ["mechanism", "injury_time", "weak_focal", "sick_contact", "device"],
    must: ["fever", "calf_pain", "immobil", "numb"],
    pe: [
      "gc_look",
      "ext_edema",
      "ext_skin",
      "ext_calf",
      "ext_motion",
      "ext_pulse",
      "neuro_sensory",
    ],
    peMore: ["neuro_mp", "heart_murmur", "chest_bs", "abd_tender"],
    peMust: ["ext_skin", "ext_pulse", "ext_motion"],
    icd: [
      on("M79.609", "Pain in unspecified limb"),
      off("R60.9", "Edema, unspecified"),
      off("L03.90", "Cellulitis, unspecified"),
      off("M25.50", "Pain in unspecified joint"),
      off("M79.89", "Other specified soft tissue disorders"),
    ],
  }),
  problem({
    id: "skin_allergy",
    label: "皮疹／癢／過敏",
    cc: "rash/itching",
    group: "外傷皮膚骨科",
    characterize: ["onset", "rash", "itch"],
    ask: [
      "allergen",
      "lip_swell",
      "dyspnea",
      "wheeze",
      "fever",
      "sore_throat",
      "vomiting",
      "diarrhea",
      "presyncope",
      "wound",
      "sick_contact",
    ],
    askMore: ["limb_pain", "anticoag", "bruise"],
    must: ["lip_swell", "dyspnea", "allergen", "presyncope", "fever"],
    pe: ["gc_look", "heent_throat", "chest_bs", "heart_rhythm", "ext_skin"],
    peMore: ["neck_stiff", "abd_tender", "ext_motion", "neck_lap"],
    peMust: ["heent_throat", "chest_bs", "ext_skin"],
    icd: [
      on("R21", "Rash and other nonspecific skin eruption"),
      off("L50.9", "Urticaria, unspecified"),
      off("T78.40XA", "Allergy, unspecified, initial encounter"),
      off("L29.9", "Pruritus, unspecified"),
      off("T78.3XXA", "Angioneurotic edema, initial encounter"),
    ],
  }),
  problem({
    id: "bleeding",
    label: "出血（鼻、牙齦、瘀青、傷口不止血）",
    cc: "bleeding",
    group: "外傷皮膚骨科",
    characterize: ["onset"],
    ask: [
      "epistaxis",
      "gum_bleed",
      "bruise",
      "hematuria",
      "hematochezia",
      "melena",
      "vag_bleed",
      "anticoag",
      "fever",
      "wt_loss",
      "head_strike",
      "dizzy",
      "presyncope",
    ],
    askMore: ["alcohol", "nsaid_steroid", "jaundice"],
    must: ["anticoag", "presyncope", "head_strike"],
    pe: ["gc_look", "heent_conj", "heent_ent", "ext_skin", "heart_rhythm", "abd_mass"],
    peMore: ["neck_lap", "rectal_dre", "abd_tender"],
    peMust: ["heent_conj", "ext_skin"],
    icd: [
      on("R58", "Hemorrhage, not elsewhere classified"),
      off("R04.0", "Epistaxis"),
      off("R23.3", "Spontaneous ecchymoses"),
    ],
  }),

  // ───────────── 其他 ─────────────
  problem({
    id: "psych",
    label: "精神（焦慮、自傷、躁動、失眠）",
    cc: "psychiatric symptom",
    ccFrom: "psych_type",
    ccMode: "replace",
    group: "精神",
    characterize: ["psych_type", "onset"],
    ask: [
      "si",
      "self_harm",
      "anxiety",
      "insomnia",
      "hallucination",
      "substance",
      "alcohol",
      "palpitation",
      "chest_pain",
      "dyspnea",
    ],
    askMore: ["fever", "headache", "head_strike", "confusion", "dm_meds_issue"],
    must: ["si", "self_harm", "substance"],
    pe: [
      "gc_look",
      "gc_gcs",
      "heent_pupil",
      "heart_rhythm",
      "chest_bs",
      "neuro_orient",
    ],
    peMore: ["neuro_mp", "neuro_cerebellar", "ext_skin", "neck_stiff"],
    peMust: ["gc_gcs", "heent_pupil", "neuro_orient"],
    icd: [
      on("F41.9", "Anxiety disorder, unspecified"),
      whenPick("R45.851", "Suicidal ideations", "psych_type", "自殺意念"),
      whenPick("R45.1", "Restlessness and agitation", "psych_type", "躁動"),
      whenPick("G47.00", "Insomnia, unspecified", "psych_type", "失眠"),
      off("T14.91XA", "Suicide attempt, initial encounter"),
    ],
  }),
];

const problemById = new Map<string, EdProblem>(ED_PROBLEMS.map((p) => [p.id, p]));

export function edProblem(id: string): EdProblem | undefined {
  return problemById.get(id);
}

export const PROBLEM_GROUP_ORDER: readonly EdProblemGroup[] = [
  "全身代謝",
  "心肺",
  "消化",
  "泌尿婦產",
  "神經",
  "五官",
  "外傷皮膚骨科",
  "精神",
];
